[tool.poetry]
name = "streamlit-modern-select"
version = "0.1.0"
description = ""
authors = ["Frank Hoffsümmer <frank.hoffsummer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
watchdog = "^4.0.0"
streamlit = "1.32.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
